### ISSUE TITLE
Cant record in fullscreen

### ISSUE THREAD

**Issue by dsv23** [sharmalay/canvas_capture#5]
Hi

really Great addon !!!
I really like the way it lets you pick what canvas to record

Heres what my problem is

I start my browser , go to a webgl website
start the addon
go to fullscreen
addon dissapears

if I come out of full screen and make my browser window smaller the 
addon sometimes  shows up

the addon is not able to see that I gone to full screen
and even if it does 
it only records at whatever size I managed to get the addon  to show up at

for example 
 I have to make my browser very small say 400 x 200 BEFORE  I can switch on the addon
if my browser is any bigger(and I dont mean full screen!) then the addon refuses to showup

can you add a setting so the user can decide what resolution to record at or at least have the addon notice that the screen size has changed because I cant record the whole screen

my screen size is 1920 x 1080 and Im using firefox 58
the biggest screen size I can get the addon to see is 1280 x 709(and therefore record at) even when Im in fullscreen

one other issue but not as major as the last one!!!
so I do the recording
then I click on the download option
a window appears asking me to either save the file or play it directly
IF I play the file, it plays , however when it finishes the file is now gone(or at least I dont know where it is!!!
However IF I save the file FIRST then all is well, but I HAVE to save it first
maybe the addon could tell me where the file is IF I choose to just play the file first without saving it

again I would just like to say THANKS for this addon

**Comment by sharmalay** [comment]
I am unable to reproduce the fullscreen disappearing behavior in either Firefox or Chrome. Since another user was able to reproduce this around the same time, maybe there was a rendering bug in that release of Firefox. I also don't have any problem arbitrarily resizing the window.

The upcoming 1.2.0 release adds the ability to list the captured videos so I think that might help with your second issue. If the new release doesn't fix the fullscreen issue for you, feel free to open a new issue with instructions on how to reproduce the bug and the details of what browser and OS you use.
